# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python37:
        python.version: '3.7'
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip
    displayName: 'Update pip'

  - script: 'python dev_setup.py'
    displayName: 'Prepare environment (install packages + dependencies + tools)'

  - script: 'python test_packages.py'
    displayName: 'pytest'


- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: echo $(Build.SourcesDirectory)
    displayName: check source directory

  - script: dir
    displayName: check contents of source directory

#  - script: cd azure-iot-hub-devicesdk
#    displayName: Go to devices
#
#  - script: dir
#    displayName: check content of this directory

  - script: |
      cd azure-iot-hub-devicesdk
      dir
      python setup.py sdist
    displayName: Go to devices and build distribution

#
#  - script: python setup.py sdist
#    displayName: 'Build sdist'
#
#  - task: PublishBuildArtifacts@1
#    displayName: 'Publish artifact: dist'
#    inputs:
#      pathtoPublish: 'dist'
#      artifactName: 'dist'
#      publishLocation: 'Azure Artifacts/TFS'
